### ISSUE TITLE
Can't get headers from an async HTTP request

### ISSUE THREAD

**Issue by TheOnlyArtz** [pikelang/Pike#20]
Hey! I'm using [this](https://pike.lysator.liu.se/generated/manual/modref/ex/predef_3A_3A/Protocols/HTTP/Session/async_get_url.html) to call async HTTP Requests and this is my code:
```pike
  Protocols.HTTP.Query APIRequest(string method, string endpoint, string route, mapping data, mapping files) {
    Standards.URI uri = Standards.URI(API_URI + endpoint);
    mixed q = Protocols.HTTP.Session()["async_" + lower_case(method) + "_url"](uri, data, constants.API->get("headers")(client));

    write("\n\n%O->->", q.con.headers); // returns `0` (NULL) and not just headers, 80% of the available keys are NULL
    return q.con;
  }
```

**Comment by TheOnlyArtz** [comment]
NOTE: Tbh what I'm trying to achieve is executing code asynchronously, even create an async task which calls the sync methods of HTTP requests.

**Comment by agehall** [comment]
Well, how did you expect that to work?

You are calling an async API to fetch some URL and then directly afterwards try to get the headers. At this point, the request may not even have begun.

The first thing you need to understand is how async programming works. You should always assume that you need to get the result in some callback unless the API docs tells you differently. If you read the documentation for Protocols.HTTP.Session, you will see that all the methods takes a good number of callbacks which are all there for a reason.

Secondly, creating a new Session for every request sort of defeats the purpose of having a session. Consider reusing it.

Lastly, since you are new to Pike, learn to not use . to index your objects. The 20+ year old convention is to use -> to index objects and . for constants such as modules.

/Marcus

**Comment by TheOnlyArtz** [comment]
Yes. There are callbacks in the docs but when I'm trying to assign them to something it says that they don't exist in the class.

**Comment by agehall** [comment]
They are most certainly there and should be used. Without callbacks, async just doesn’t work.

**Comment by poppa** [comment]
@TheOnlyArtz You can take a look at [`Protocols.HTTP.Promise`](https://github.com/pikelang/Pike/blob/master/lib/modules/Protocols.pmod/HTTP.pmod/Promise.pmod) to get some inspiration. **NOTE!** This module is not yet part of the official Pike release and only available in the development branch. (BTW: this module should really be finalized since the Promise-API is pretty stable by now).

I guess the `_->callback_*` stuff is `protected`, hence why you can't assign to them straight ahead. What you want to use is probably the [`set_callback()`](https://pike.lysator.liu.se/generated/manual/modref/ex/predef_3A_3A/Protocols/HTTP/Session/Request/set_callbacks.html) method.

**Comment by TheOnlyArtz** [comment]
Thank you for the help guys!
@poppa Hey, can you provide any example of using the HTTP.Promise?

**Comment by poppa** [comment]
@TheOnlyArtz As I wrote, the module isn't available in Pike 8.0, but if you chose to use it manually the various methods `Protocols.HTTP.Promise.{get_url, post_url, delete_url, put_url}()` will simply return a [`Concurrent.Future`](https://pike.lysator.liu.se/generated/manual/modref/ex/predef_3A_3A/Concurrent/Future.html)-object. 

There are also examples of usage in source file I linked to:

```pike
Protocols.HTTP.Promise.Arguments a1;

a1 = Protocols.HTTP.Promise.Arguments(([
  "headers" : ([ "X-Some-Header" : "A Header Value" ])
]));

Concurrent.Future query;
query = Protocols.HTTP.Promise.get_url("https://some-domain.com", a1);

query->on_success(lambda (Protocols.HTTP.Promise.Result res) {
  werror("Result status code: %O\n", res->status_code);
  werror("Result data (first fifty bytes): %O\n", res->get()[0..50]);
  werror("Result object: %O\n", res);
});

query->on_failure(lambda (Protocols.HTTP.Promise.Result err) {
  werror("Query failed: %O\n", err);
});
``` 

Or something along that line.

**Comment by TheOnlyArtz** [comment]
> @TheOnlyArtz As I wrote, the module isn't available in Pike 8.0, but if you chose to use it manually the various methods `Protocols.HTTP.Promise.{get_url, post_url, delete_url, put_url}()` will simply return a [`Concurrent.Future`](https://pike.lysator.liu.se/generated/manual/modref/ex/predef_3A_3A/Concurrent/Future.html)-object.
> 
> There are also examples of usage in source file I linked to:
> 
> ```pike
> Protocols.HTTP.Promise.Arguments a1;
> 
> a1 = Protocols.HTTP.Promise.Arguments(([
>   "headers" : ([ "X-Some-Header" : "A Header Value" ])
> ]));
> 
> Concurrent.Future query;
> query = Protocols.HTTP.Promise.get_url("https://some-domain.com", a1);
> 
> query->on_success(lambda (Protocols.HTTP.Promise.Result res) {
>   werror("Result status code: %O\n", res->status_code);
>   werror("Result data (first fifty bytes): %O\n", res->get()[0..50]);
>   werror("Result object: %O\n", res);
> });
> 
> query->on_failure(lambda (Protocols.HTTP.Promise.Result err) {
>   werror("Query failed: %O\n", err);
> });
> ```
> 
> Or something along that line.

This is exactly what I was looking for? any ETA for it being in the stable release or even any instructions on how to use it "manually"?

**Comment by poppa** [comment]
Sorry for the delay. 

I can't give you an ETA of when it would possibly be part of the stable release. That code pretty much hasn't been touched since I wrote it when the `Concurrent.{Promise/Future}` API was created, and would probably need some touches here and there to become viable for a stable release.

There are different ways to use Pike modules.

1) **Locally**:  If you have lets say `app.pike` and `MyModule.pmod` in the same directory, and say `MyModule.pmod` has a class named `MyClass` in it, you would reference `MyClass` from `app.pike` by:

```
.MyModule.MyClass obj = .MyModule.MyClass();
```
  
Note the beginning `.` (dot). 

You could also do:

```
import "."; // Import all modules in the current directory

// Now, no beginning dot is needed
MyModule.MyClass obj = MyModule.MyClass();
```

You can also pass a compile time flag (`-M`) with module paths to Pike when you start your app:

```
pike -M. app.pike
pike -M/path/to/modules app.pike
```

2) **Globally**: By setting the environment variable `PIKE_MODULE_PATH` to point to some directory, Pike will always look in that directory for Pike modules.

So if you have, for example, `~/pike-modules/MyModule.pmod` and set `PIKE_MODULE_PATH=~/pike-modules`, you will always have access to:

```
// Some code in some Pike app somewhere on your system
MyModule.MyClass obj = MyModule.MyClass();
```

## Howto

So in this case, if you want to use the `Protocols.HTTP.Promise` module, do something along the line of:

1) Create a directory where you can put all generic custom Pike modules, for instance `C:\lib\pike-modules`.
2) Create the environment variable `PIKE_MODULE_PATH` to point to that directory: `PIKE_MODULE_PATH=C:\lib\pike-modules`
3) In `C:\lib\pike-modules` create the directory structure `Protocols.pmod\HTTP.pmod` (note, these are directory names) and create `Promise.pmod` (a file) in there and copy and past the contents of [`Protocols.HTTP.Promise`](https://github.com/pikelang/Pike/blob/master/lib/modules/Protocols.pmod/HTTP.pmod/Promise.pmod) into that file. So this will give you: `C:\lib\pike-modules\Protocols.pmod(dir)\HTTP.pmod(dir)\Promise.pmod(file)`.
4) Now you should have access to `Protocols.HTTP.Promise` in you application.

Hope this helps :)

**Comment by TheOnlyArtz** [comment]
Thank you! @poppa That will do, I got another question which I don't want to open an issue dedicated to it because it's a small one:

Is there any equivalent to the Javascript `rest` operator? also known as `...` ?
example of usage (in Pike)
```pike
function emit(mixed ... data) {
  test(...data);
}

function test(string client, string name) {
  write(name);
}

emit("Client", 'Jimmy"); // -> Will write "Jimmy" to the console
```
of course it will throw an error because `...` is not a thing, but is there this kind of thing in Pike?

**Comment by grubba** [comment]
Sounds like you want the splice operator (``@``, https://pike.lysator.liu.se/docs/man/chapter_4.html#7) .
Example taken from the master:
```
void resolv_debug (sprintf_format fmt, sprintf_args... args)
{
  string pad = "  " * GET_RESOLV_MSG_DEPTH;
  if (sizeof (args)) fmt = sprintf (fmt, @args);
  if (fmt[-1] == '\n')
    fmt = pad + replace (fmt[..<1], "\n", "\n" + pad) + "\n";
  else
    fmt = pad + replace (fmt, "\n", "\n" + pad);
  if (!werror) werror = Files()->_stderr->write;
  werror (fmt);
}
```

**Comment by TheOnlyArtz** [comment]
Wow, thank you guys very much! I'm so impressed about Pike, you are amazing! keep up the good job.

**Comment by TheOnlyArtz** [comment]
> Sorry for the delay.
> 
> I can't give you an ETA of when it would possibly be part of the stable release. That code pretty much hasn't been touched since I wrote it when the `Concurrent.{Promise/Future}` API was created, and would probably need some touches here and there to become viable for a stable release.
> 
> There are different ways to use Pike modules.
> 
> 1. **Locally**:  If you have lets say `app.pike` and `MyModule.pmod` in the same directory, and say `MyModule.pmod` has a class named `MyClass` in it, you would reference `MyClass` from `app.pike` by:
> 
> ```
> .MyModule.MyClass obj = .MyModule.MyClass();
> ```
> Note the beginning `.` (dot).
> 
> You could also do:
> 
> ```
> import "."; // Import all modules in the current directory
> 
> // Now, no beginning dot is needed
> MyModule.MyClass obj = MyModule.MyClass();
> ```
> You can also pass a compile time flag (`-M`) with module paths to Pike when you start your app:
> 
> ```
> pike -M. app.pike
> pike -M/path/to/modules app.pike
> ```
> 1. **Globally**: By setting the environment variable `PIKE_MODULE_PATH` to point to some directory, Pike will always look in that directory for Pike modules.
> 
> So if you have, for example, `~/pike-modules/MyModule.pmod` and set `PIKE_MODULE_PATH=~/pike-modules`, you will always have access to:
> 
> ```
> // Some code in some Pike app somewhere on your system
> MyModule.MyClass obj = MyModule.MyClass();
> ```
> ## Howto
> So in this case, if you want to use the `Protocols.HTTP.Promise` module, do something along the line of:
> 
> 1. Create a directory where you can put all generic custom Pike modules, for instance `C:\lib\pike-modules`.
> 2. Create the environment variable `PIKE_MODULE_PATH` to point to that directory: `PIKE_MODULE_PATH=C:\lib\pike-modules`
> 3. In `C:\lib\pike-modules` create the directory structure `Protocols.pmod\HTTP.pmod` (note, these are directory names) and create `Promise.pmod` (a file) in there and copy and past the contents of [`Protocols.HTTP.Promise`](https://github.com/pikelang/Pike/blob/master/lib/modules/Protocols.pmod/HTTP.pmod/Promise.pmod) into that file. So this will give you: `C:\lib\pike-modules\Protocols.pmod(dir)\HTTP.pmod(dir)\Promise.pmod(file)`.
> 4. Now you should have access to `Protocols.HTTP.Promise` in you application.
> 
> Hope this helps :)

I've set the structure as you've suggested
![image](https://user-images.githubusercontent.com/30025874/56375359-f077f100-620d-11e9-84de-f731761f0629.png)

And I've set the environment variables as suggested
![image](https://user-images.githubusercontent.com/30025874/56375383-0b4a6580-620e-11e9-96eb-e4b6fce0d9c5.png)

But interpreter says that `Promise` is not present in the HTTP module
